Begin implementing controller
This commit simply puts the page infrastructure in place:

* Require the AngularJS package
* Indicate that the entire document is an AngularJS app (`ng-app`)
* Control the document `body` using an `ng-controller` named
`MainController`

Because I've not yet defined the `MainController` function (it need
**not** be a class), rendering the page prints not the value of the
AngularJS binding expression, `{{message}}`, but the literal expression
itself. Furthermore, the browser developer tools report many errors:

    Error: [ng:areq] http://errors.angularjs.org/1.5.8/ng/areq?p0=MainController&p1=not%20a%20function%2C%20got%20undefined
	at angular.min.js:6
	at sb (angular.min.js:23)
	at Pa (angular.min.js:23)
	at angular.min.js:89
	at ag (angular.min.js:72)
	at p (angular.min.js:64)
	at g (angular.min.js:58)
	at g (angular.min.js:58)
	at angular.min.js:58
	at angular.min.js:21